services:
  - type: web
    name: web-learning-platform
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
